### ISSUE TITLE
Setup git-flow

### ISSUE THREAD

**Issue by ChristofLee** [nirmankarta/eddyst.one#16]
This project has multiple people working on it and it might make things easier with some processes.

[Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)

It would be good to protect *Master* and *Dev* and only allow pushing of *Feature* branches.

This way the owner could handle *Releases* to Master.

**Comment by PrabhanshuAttri** [comment]
Eddyst.one is just a small project. I think this will be more useful in [PyBeacon](https://github.com/nirmankarta/PyBeacon/). Let's discuss it on slack. Thanks.
